name = "FastSolvers"
uuid = "afc03370-3a10-4444-b401-158123c3c69f"
version = "0.1.0"
authors = ["Anant Thazhemadam <anant.thazhemadam@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.10"
julia = "1.10"
